### ISSUE TITLE
[Feature]: Support for Microsoft Edge Add-ons

### ISSUE THREAD

**Issue by bam1279** [bam1279/share-switch#6]
### Prerequisites

- [X] I have verified that this issue is not a duplicate. (Search [here](https://github.com/bam1279/share-switch/issues)  to find out.)

### Is your feature request related to a problem? Please describe.

The ShareSwitch extension is currently only available through the Chrome Web Store.
I find it inconvenient that users cannot access this extension directly from the Microsoft Edge addons store.

### Describe the solution you'd like

I intend to make this extension officially available in the Microsoft Edge Add-ons Store as well.

### Describe alternatives you've considered

An alternative solution would be to continue using the Chrome Web Store to install the extension on Edge.
However, this is not ideal as it requires additional steps.

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by bam1279** [comment]
## ToDo
- [x] Perform operational verification with Edge
- [x] If there are any problems, fix them
- [x] Register as a Microsoft Edge extension developer
- [x] Submit the extension to the Microsoft Edge Add-ons website

**Comment by bam1279** [comment]
ShareSwitch is now available on the Microsoft Edge Add-ons website.
https://microsoftedge.microsoft.com/addons/detail/shareswitch/pmhkogjeogmpenpjeciapeebfkbnamni?hl=en
