### ISSUE TITLE
[Feature]: Firefox compatibility

### ISSUE THREAD

**Issue by bam1279** [bam1279/share-switch#7]
### Prerequisites

- [X] I have verified that this issue is not a duplicate. (Search [here](https://github.com/bam1279/share-switch/issues)  to find out.)

### Is your feature request related to a problem? Please describe.

Currently, the ShareSwitch extension is not available for Firefox users, which limits the usefulness of the extension for those who prefer or exclusively use this browser.

### Describe the solution you'd like

I intend to make this extension compatible with Firefox.

### Do you want to implement this feature yourself?

- [X] Yes, I will implement this by myself and send a pull request

**Comment by bam1279** [comment]
## ToDo 
 
- [ ] Perform operational verification in Firefox
- [ ] If there are any problems, fix them
- [ ] Register with the Mozilla Developer Hub, sign, and undergo review
- [ ] Submit to addons.mozilla.org
